# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/Autoqatester
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# Hibernate / JPA Settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true

screenshot.storage.path=C:/qa_screenshots/